from django.db import models
# Create your models here.

SEX_LIST = (
    ('', 'Choose...'),
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Others')
)
BOOK_LIST = (
    ('', 'Choose...'),
    ('R', 'Register'),
    ('M', 'Memo'),
    ('O', 'Others')
)

UNIT_LIST = (
    ('', 'Choose...'),
    ('P', 'Pcs'),
    ('D', 'Dozon'),
    ('O', 'Others')
)

TRAN_LIST = (
    ('', 'Choose...'),
    ('PH', 'Purchase'),
    ('IS', 'Issue'),
    ('DM', 'Damage'),
    ('O', 'Others')
)
EDU_LIST = (
    ('', 'Choose...'),
    ('PSC', 'PSC'),
    ('JSC', 'JSC'),
    ('SSC', 'SSC'),
    ('HSC', 'HSC'),
    ('Honors', 'Honors'),
    ('Masters', 'Masters')
)
INSTFRQ_LIST = (
    ('', 'Choose...'),
    ('W', 'Weekly'),
    ('M', 'Monthly'),
    ('Q', 'Quartly'),
    ('H', 'Half Yearly'),
    ('Y', 'Yearly'),
)

HOL_LIST = (
    ('', 'Choose...'),
     ('FRI', 'Friday'),
    ('SAT', 'Saturday'),
    ('SUN', 'Sunday'),
    ('MON', 'Monday'),
    ('TUES', 'Tuesday'),
    ('WED', 'Wednesday'),
    ('THU', 'Thursday')
)
EMP_STATUS_LIST = (
    ('', 'Choose...'),
    ('A', 'Active'),
    ('I', 'Inactive'),
    ('O', 'Others')
)
CLTYPE_LIST = (
    ('', 'Choose...'),
    ('I', 'Individual'),
    ('C', 'Corporate'),
    ('J', 'Joint'),
    ('O', 'Others')
)
CLCAT_LIST = (
    ('', 'Choose...'),
    ('1', 'GOVERMENT SECTOR'),
    ('2', 'PUBLIC SECTOR'),
    ('3', 'PRIVATE SECTOR'),
    ('4', 'OTHERSECTORS')
)
CLSEGMENT_LIST = (
    ('', 'Choose...'),
    ('1133','Academy, Research Institute, Development Institutes, Training Centre, and Council'),
    ('113340','Accident Research Institute (ARI), Bangladesh'),
    ('902466','Advertising Industry and modeling (print modeling, TV commercials, ramp modeling, catwalk, fashion-show)'),
    ('121519','Agrani SME Financing Company Limited'),
    ('901001','Agricultural Farms (Nursery, Horticulture, Apiculture etc)'),
    ('113446','Agriculture Information Service'),
    ('211','Agriculture, Fishing & Livestock'),
    ('2124','Agro-based and agro-processing industry'),
    ('904003','Air Transport'),
    ('113499','All Other Boards/Centres'),
    ('121710','Ansar-VDP Unnayan Bank'),
    ('113435','Anti Corruption Commission'),
    ('123425','Ashuganj Power Station Company Ltd (APSCL)'),
    ('902138','Assembling Industry'),
    ('902481','Audit and Accounting Firm/CA Firm/ Credit Rating Company'),
    ('902465','Auto mobile service including CNG conversion centre.'),
    ('113','Autonomous and Semi-Autonomous Bodies'),
    ('113416','BARID Multipurpose Development Authority, Rajshahi'),
    ('113422','Bandarban Hill District Council'),
    ('113209','Bangabandhu Sheikh Mujib Medical University'),
    ('113222','Bangabandhu Sheikh Mujibur Rahman Agricultural University'),
    ('123713','Bangabandhu Sheikh Mujibur Rahman Novo Theatre'),
    ('113226','Bangabandhu Sheikh Mujibur Rahman Science & Technology University'),
    ('113303','Bangla Academy'),
    ('113301','Bangladesh Academy for Rural Development (BARD)'),
    ('113458','Bangladesh Accreditation Board'),
    ('113402','Bangladesh Agricultural Development Corporation (BADC)'),
    ('113306','Bangladesh Agricultural Research Institute (BARI)'),
    ('113216','Bangladesh Agricultural University, Mymensingh'),
    ('113385','Bangladesh Agriculture Research Council (BARC)'),
    ('112085','Bangladesh Air Force'),
    ('112079','Bangladesh Ansar and VDP'),
    ('113451','Bangladesh Applied Nutrition And Human Resources Development Board'),
    ('112083','Bangladesh Army'),
    ('113401','Bangladesh Atomic Energy Commission'),
    ('113503','Bangladesh Betar'),
    ('122810','Bangladesh Biman Corporation'),
    ('113413','Bangladesh Bridge Authority'),
    ('112068','Bangladesh Bureau of Statistics'),
    ('123707','Bangladesh Cable Industries Corporation'),
    ('123715','Bangladesh Cable Shilpa Limited'),
    ('1212','Bangladesh Chemical Industries Corporation and Related Enterprises'),
    ('113332','Bangladesh Civil Service Administration Academy'),
    ('113327','Bangladesh Co-operative Academy'),
    ('112081','Bangladesh Coast Guard'),
    ('113346','Bangladesh College of Physicians & Surgeons'),
    ('113387','Bangladesh Computer Council (BCC)'),
    ('113307','Bangladesh Council of Scientific & Industrial Research (BCSIR)'),
    ('112054','Bangladesh Education Engineering Department'),
    ('113431','Bangladesh Energy Regulatory Commission (BERC)'),
    ('113438','Bangladesh Export Processing Zone Authority (BEPZA)'),
    ('123702','Bangladesh Film Development Corporation'),
    ('123110','Bangladesh Fish Development Corporation'),
    ('113338','Bangladesh Fisheries Research Institute (BFRI)'),
    ('113470','Bangladesh Folk Arts & Craft Foundation, Sonargaon'),
    ('113362','Bangladesh Foreign Trade Institute (BFTI)'),
    ('112048','Bangladesh Forest Department'),
    ('122905','Bangladesh Forest Industries Development Corporation'),
    ('113342','Bangladesh Forest Research Institute'),
    ('112088','Bangladesh Form and Publications Office'),
    ('123705','Bangladesh Freedom Fighters Welfare Trust'),
    ('113482','Bangladesh Girls Guide Association'),
    ('121521','Bangladesh Government Islamic Investment Bond'),
    ('112075','Bangladesh Govt. Press (BG Press)'),
    ('113409','Bangladesh Handloom Board'),
    ('113425','Bangladesh Haor And Wetland Development Board'),
    ('113345','Bangladesh Health Professionals Institute (BHPI)'),
    ('113445','Bangladesh Hi-Tech Park Authority'),
    ('113448','Bangladesh Homoeopathic Board'),
    ('121100','Bangladesh House Building Finance Corporation (HBFC)'),
    ('113373','Bangladesh Industrial Technical Assistance Centre (BITAC), Tejgaon, Dhaka'),
    ('121520','Bangladesh Infrastructure Finance Fund Limited'),
    ('123210','Bangladesh Inland Water Transport Authority (BIWTA)'),
    ('123220','Bangladesh Inland Water Transport Corporation (BIWTC)'),
    ('113344','Bangladesh Institute of Bank Management (BIBM)'),
    ('113347','Bangladesh Institute of Development Studies (BIDS)'),
    ('113372','Bangladesh Institute of International and Strategic Studies'),
    ('113348','Bangladesh Institute of International and Strategic Studies (BIISS)'),
    ('113349','Bangladesh Institute of Management (BIM)'),
    ('113335','Bangladesh Institute of Nuclear Agriculture, Mymensingh'),
    ('113371','Bangladesh Institute of Textile Technology (BITT), Tangail'),
    ('113322','Bangladesh Insurance Academy'),
    ('113433','Bangladesh Judicial Service Commission'),
    ('122510','Bangladesh Jute Mills Corporation and Related Enterprises'),
    ('113333','Bangladesh Jute Research Institute (BJRI)'),
    ('113370','Bangladesh Krira Shikkha Protisthan (BKSP)'),
    ('113337','Bangladesh Livestock Research Institute'),
    ('123718','Bangladesh Machine Tools Factory Limited'),
    ('113102','Bangladesh Madrasha Education Board'),
    ('112074','Bangladesh Marine Academy'),
    ('113378','Bangladesh Medical & Dental Council (BMDC)'),
    ('113380','Bangladesh Medical Research Council'),
    ('112072','Bangladesh Missions in Abroad'),
    ('113473','Bangladesh NGO Foundation'),
    ('113430','Bangladesh National Commission of UNESCO'),
    ('113487','Bangladesh National Herbarium'),
    ('113461','Bangladesh National Medical Council'),
    ('113311','Bangladesh National Museum'),
    ('112071','Bangladesh National Parliament (Jatio Sangshad Secretariat)'),
    ('113480','Bangladesh National Science & Technical Documentation Centre (BANSDOC)'),
    ('113383','Bangladesh National Social Welfare Council'),
    ('112084','Bangladesh Navy'),
    ('113381','Bangladesh Nursing Council'),
    ('122620','Bangladesh Oil, Gas & Mineral Corporation & related enterprises'),
    ('113205','Bangladesh Open University (BOU)'),
    ('112082','Bangladesh Ordinance Factories'),
    ('113423','Bangladesh Overseas Employment Service Limited (BOESEL)'),
    ('123701','Bangladesh Parjatan Corporation'),
    ('122610','Bangladesh Petroleum Corporation & related enterprises'),
    ('1214','Bangladesh Petroleum Corporation and Bangladesh Oil, Gas & Mineral Corporation and Related Enterprises'),
    ('113368','Bangladesh Petroleum Institute'),
    ('112076','Bangladesh Police'),
    ('112100','Bangladesh Post Office (except Savings Bank Scheme)'),
    ('112200','Bangladesh Post Office Savings Bank Scheme'),
    ('122700','Bangladesh Power Development Board'),
    ('1215','Bangladesh Power Development Board & Related Enterprises'),
    ('113462','Bangladesh Press Council'),
    ('113437','Bangladesh Public Service Commission'),
    ('122902','Bangladesh Railway'),
    ('113308','Bangladesh Rice Research Institute (BRRI)'),
    ('113442','Bangladesh Road Transport Authority (BRTA)'),
    ('122904','Bangladesh Road Transport Corporation (BRTC)'),
    ('113412','Bangladesh Rural Development Board (BRDB)'),
    ('113358','Bangladesh Rural Development Training Institute (BRDTI)'),
    ('909650','Bangladesh Samabaya Bank Ltd'),
    ('113502','Bangladesh Sangbad Sangstha (BSS)'),
    ('113483','Bangladesh Scouts'),
    ('112086','Bangladesh Secretariat'),
    ('113365','Bangladesh Seri cultural Research and Training Institute'),
    ('113410','Bangladesh Sericulture Board'),
    ('123709','Bangladesh Services Ltd.'),
    ('113304','Bangladesh Shilpakala Academy'),
    ('122820','Bangladesh Shipping Corporation'),
    ('113325','Bangladesh Shishu Academy'),
    ('113341','Bangladesh Silk Research and Training Institute (BSRTI), Rajshahi'),
    ('123610','Bangladesh Small & Cottage Industries Corporation (BSCIC)'),
    ('113390','Bangladesh Space Research and Remote Sensing Organisation (SPARRSO)'),
    ('113454','Bangladesh Sports Control Board'),
    ('113309','Bangladesh Standards & Testing Institution (BSTI)'),
    ('1213','Bangladesh Steel & Engineering Corporation and Related Enterprises'),
    ('123530','Bangladesh Sthal Bandar Katripaksha'),
    ('123714','Bangladesh Submarine Cable Company Limited'),
    ('1211','Bangladesh Sugar & Food Industries Corporation and Related Enterprises'),
    ('113336','Bangladesh Sugarcane Research Institute, (BSRI)'),
    ('112090','Bangladesh Supreme Court (Including High Court)'),
    ('123708','Bangladesh Tannery Industries Corporation'),
    ('113428','Bangladesh Tariff Commission'),
    ('123120','Bangladesh Tea Board'),
    ('113456','Bangladesh Tea Plantation Employees Provident Fund Trustee Board'),
    ('113339','Bangladesh Tea Research Institute (BTRI)'),
    ('113103','Bangladesh Technical Education Board'),
    ('113436','Bangladesh Telecommunication Regulatory Commission (BTRC)'),
    ('122903','Bangladesh Telecommunications Company Limited (BTCL) (Including Teletalk)'),
    ('113501','Bangladesh Television/BTV World/ Sangshad Bangladesh TV'),
    ('122100','Bangladesh Textile Mills Corporation & Related Enterprises'),
    ('113227','Bangladesh Textile University'),
    ('113449','Bangladesh Tobacco Development Board'),
    ('113208','Bangladesh University of Engineering & Technology'),
    ('113228','Bangladesh University of Professional'),
    ('113312','Bangladesh Veterinary Council'),
    ('123310','Bangladesh Water Development Board'),
    ('113229','Barisal University'),
    ('902154','Battery Manufacturing Industries'),
    ('902454','Beauty Parlours/ Saloons/ Health Club/Fitness centre'),
    ('113230','Begum Rokeya University'),
    ('113466','Benevolent Funds'),
    ('902143','Beverage and Soft Drinks manufacturing Companies'),
    ('113104','Board of Intermediate and Secondary Educations'),
    ('112069','Board of Investment Bangladesh'),
    ('113453','Board of Unani & Ayurvedic Council'),
    ('112078','Border Guard Bangladesh'),
    ('902133','Bricks Manufacturers and Sand elevators'),
    ('909720','Brokerage Houses/ (Share & Security Trading Houses)'),
    ('113475','Buddhist Welfare Trust'),
    ('112065','Bureau of Manpower, Employment and Training'),
    ('112066','Bureau of Non-formal Education'),
    ('903009','Businessmen/Industrialist'),
    ('906001','Buying House'),
    ('113202','Cadet Colleges'),
    ('902469','Caterers /Decorators/Sound & Lighting rental business'),
    ('902131','Cement Factories'),
    ('909300','Central Co-operative Bank'),
    ('113364','Central Development Resources Development Institute'),
    ('113310','Central Public Library'),
    ('902132','Ceramic Industries'),
    ('902461','Chain Super Market/Shopping Mall'),
    ('914060','Chambers of Industries'),
    ('902130','Chemical and Chemical Products Industries'),
    ('113406','Chittagong Development Authority'),
    ('113403','Chittagong Hill Tracts Development Board'),
    ('113419','Chittagong Hill Tracts Regional Council'),
    ('123510','Chittagong Port Authority'),
    ('113212','Chittagong University'),
    ('113219','Chittagong University of Engineering & Technology'),
    ('113231','Chittagong Veterinary and Animal Sciences University'),
    ('113476','Christian Welfare Trust'),
    ('902483','Cinema Hall/Cineplex'),
    ('902482','Cinema Studio'),
    ('123704','Civil Aviation Authority of Bangladesh'),
    ('902455','Clearing and Forwarding (C and F) Agents'),
    ('902114','Coconut oil production industries'),
    ('902453','Cold-Storages'),
    ('113232','Comilla University'),
    ('213','Commerce & Trade (excluding individual businessmen)'),
    ('902470','Community Centers/ Convention centers/Auditorium'),
    ('113486','Comprehensive Disaster Management Program'),
    ('905000','Construction Companies'),
    ('902486','Consultancy & Supervisory Farms'),
    ('902488','Contractor and Supplier farms'),
    ('112062','Copyright Office'),
    ('902116','Cosmetics & Toiletries Industries'),
    ('902210','Cottage Industries'),
    ('113457','Cotton Development Board'),
    ('113384','Council of Bangladesh Institute of Technology'),
    ('902440','Courier Services & Express Mail Services'),
    ('113376','Coxs Bazar Cultural Centre'),
    ('113484','Cyclone Preparedness Programme (CPP)'),
    ('901003','Dairy Farms'),
    ('112033','Department of Agricultural Extension'),
    ('112053','Department of Agricultural Marketing'),
    ('112051','Department of Architecture'),
    ('112034','Department of Co-operative'),
    ('112050','Department of Disaster Management'),
    ('112055','Department of Environment'),
    ('112052','Department of Explosive'),
    ('112039','Department of Film and Publications'),
    ('112043','Department of Fire Service and Civil Defense'),
    ('112046','Department of Fisheries'),
    ('112041','Department of Immigration and Passports'),
    ('112047','Department of Livestock Services'),
    ('112030','Department of Local Government & Engineering (LGED)'),
    ('112038','Department of Mass Communication'),
    ('112044','Department of Narcotics Control'),
    ('112045','Department of Patents, Designs and Trademarks'),
    ('112042','Department of Prisons'),
    ('112049','Department of Shipping'),
    ('112056','Department of Textile'),
    ('112032','Department of Women Affairs'),
    ('112036','Department of Youth Development'),
    ('113465','Development Funds'),
    ('113468','Development Works Program Fund'),
    ('123415','Dhaka Electric Supply Authority (DESA)'),
    ('123420','Dhaka Electric Supply Company (DESCO)'),
    ('123445','Dhaka Power Distribution Company Ltd (DPDCL)'),
    ('113418','Dhaka Transport Co-ordination Authority (DTCA)'),
    ('113210','Dhaka University'),
    ('113218','Dhaka University of Engineering & Technology'),
    ('112029','Directorate General of Defense Purchase'),
    ('112027','Directorate General of Drug Administration'),
    ('112028','Directorate General of Family Planning'),
    ('112026','Directorate General of Forces Intelligence (DGFI)'),
    ('112015','Directorate of Archaeology'),
    ('112021','Directorate of Archives and Libraries'),
    ('112016','Directorate of Bangladesh Family Planning'),
    ('112020','Directorate of Bangladesh Survey'),
    ('112022','Directorate of Govt. Accommodation'),
    ('112001','Directorate of Health'),
    ('112024','Directorate of Inspection and Audit of Ministry of Education'),
    ('112005','Directorate of Jute'),
    ('112007','Directorate of Labor'),
    ('112008','Directorate of Land Record and Survey'),
    ('112013','Directorate of Livestock'),
    ('112019','Directorate of Meteorology'),
    ('112006','Directorate of National Consumer Rights Protection'),
    ('112004','Directorate of National Savings'),
    ('112018','Directorate of Nursing Services'),
    ('112003','Directorate of Primary Education'),
    ('112017','Directorate of Printing, Stationary, Forms and Publication'),
    ('112010','Directorate of Public Health and Engineering'),
    ('112002','Directorate of Relief and Rehabilitiation'),
    ('112011','Directorate of Secondary and Higher Secondary Education'),
    ('112012','Directorate of Social Welfare'),
    ('112014','Directorate of Sports'),
    ('112025','Directorate of Technical Education'),
    ('112064','Disaster Management Bureau'),
    ('902144','Distilleries, Mineral & Drinking Water purifying industries'),
    ('112091','District Judge Court (Including Other Courts in District)'),
    ('914058','District/Upazila Associations'),
    ('123712','Dock Labour Management Board, Bagerhat'),
    ('123711','Dock Labour Management Board, Chittagong'),
    ('902231','EPZ Industries (Type A)'),
    ('902232','EPZ Industries (Type B)'),
    ('902233','EPZ Industries (Type C)'),
    ('113434','Election Commission Bangladesh'),
    ('123430','Electricity Generation Company of Bangladesh Ltd (EGCB)'),
    ('902150','Electronic Goods Manufacturing/Assembling Industries (TV, Computer etc)'),
    ('122420','Engineering and Ship Building Industries'),
    ('902410','Entertainment (Amusement Park, Theme park, ecopark, zoo etc.) Services'),
    ('121516','Equity Entrepreneurship Fund'),
    ('123716','Essential Drugs Company Limited'),
    ('113426','Executive Cell, BEPZA'),
    ('113411','Export Promotion Bureau'),
    ('903020','Exporters'),
    ('901009','Farmer/Fishermen'),
    ('902141','Fertilizer Company'),
    ('122310','Fertilizer, Chemical & Pharmaceutical Industries'),
    ('902458','Filling Stations (Petrol pump, CNG Station)'),
    ('224','Financial Auxiliaries'),
    ('22','Financial Corporations'),
    ('902510','Fish feed and fish meal processing for poultry and livestock'),
    ('901002','Fishing Farms ( Hatchery, Shrimp Culture etc)'),
    ('111000','Food Ministry (Including food divisions/directorates)'),
    ('902124','Food Processing Industry (PRAN, AFTAB, BD-Food etc)'),
    ('122220','Food and Allied Industries'),
    ('912050','Foreign Individuals'),
    ('23','Foreign Offices/ Embassies/Enterprises/Companies/Liaison Offices/Farms/NGOs'),
    ('912051','Foreign Offices/ Embassies/Enterprises/Companies/Liaison Offices/Farms/NGOs (Excluding Multinational Companies incorporated in Bangladesh)'),
    ('113313','Foreign Service Academy'),
    ('902472','Freight Forwarders'),
    ('902503','Fruits processing including vegetables. (Tomato, guava, jackfruit, lichie, pineapple, coconut etc.)'),
    ('902122','Furniture, Fixture, Particle Boards and Other Wood product manufacturers'),
    ('902155','Garments Accessories manufacturing industries (Zipper, Button etc)'),
    ('2122','Gas/Electricity/Power Generating Companies'),
    ('112073','Geological Survey of Bangladesh'),
    ('902134','Glass and Glassware Products Factories'),
    ('1132','Government Educational Institutions'),
    ('113201','Government Schools, Colleges, University College & Madrashas'),
    ('11','Government Sector'),
    ('124500','Gram Parishad'),
    ('909600','Grameen Bank'),
    ('902484','Graphic Designers'),
    ('121517','Grihayan Tahobill'),
    ('113224','Hajee Mohammad Danesh Science & Technology University'),
    ('112063','Hajj Office'),
    ('902230','Handicrafts Factories'),
    ('902220','Handloom Factories'),
    ('112040','Health Engineering Department'),
    ('113474','Hindu Welfare Trust'),
    ('113469','Horticulture Export Development Foundation (Hortex Foundation)'),
    ('902126','Hosiery Factories'),
    ('902420','Hospitals, Clinics, Diagnostic Centers and Other Health Services'),
    ('123710','Hotels International Ltd. (3 Stars & above)'),
    ('25','Households ( individual customers)'),
    ('915001','Housewife'),
    ('113334','Housing & Building Research Institute'),
    ('905500','Housing Companies or Societies/Land Developers'),
    ('122630','Hydrocarbon Unit, Bangladesh'),
    ('902430','IT-based activities (system analysis, design, developing system solutions, Grameen Solution, information service, call centre service, offshore develo'),
    ('902151','Ice Factory'),
    ('903010','Importers'),
    ('903030','Importers and Exporters'),
    ('902473','Indenting firms'),
    ('212','Industries'),
    ('121501','Infrastructure Development Company Limited (IDCOL)'),
    ('113350','Institute of Chartered Accountants of Bangladesh (ICAB)'),
    ('113351','Institute of Cost & Management Accountants of Bangladesh (ICMA)'),
    ('113318','Institute of Public Health And Hospital'),
    ('113315','Institute of Public Health and Nutrition'),
    ('113366','Institute of Water Modeling'),
    ('113207','Institutes of Technology(Including Polytechnic Institutes)'),
    ('909100','Insurance Companies'),
    ('125','Insurance Companies and Pension Funds (ICPF)-Public'),
    ('223','Insurance Companies and Pension Funds-Private'),
    ('113441','Insurance Development and Regularity Authority (IDRA)'),
    ('902487','Interior Design & Decorators and other engineering consultancy farms'),
    ('113357','International Mother Language Institute'),
    ('113481','Investment Advisory Centre of Bangladesh'),
    ('909210','Investment Companies'),
    ('121300','Investment Corporation of Bangladesh (ICB)'),
    ('113305','Islamic Foundation, Bangladesh'),
    ('113217','Islamic University, Kushtia'),
    ('909730','Issue manager, Under-writer, Asset Management Company etc.'),
    ('113233','Jagannath University'),
    ('113213','Jahangirnagar University'),
    ('113234','Jatiya Kabi Kazi Nazrul Islam University'),
    ('113382','Jatiya Mohila Sangstha'),
    ('113235','Jessore Science & Technology University'),
    ('121700','Jiban Bima Corporation'),
    ('113429','Joint River Commission'),
    ('113360','Judicial Administration Training Institute'),
    ('113450','Jute Industries Development Board'),
    ('902110','Jute Mills/Jute products Manufacturing Industries (rope, thread, twain, canvass, bag, carpet, etc.)'),
    ('902463','Jwelery Services'),
    ('121720','Karma Sangsthan Bank'),
    ('113421','Khagrachori Hill District Council'),
    ('113328','Khudro Nri Gosthi Cultural Academy, Netrokona'),
    ('113352','Khudro Nri Gosthi Cultural Institute, Rangamati & Bandarban'),
    ('113407','Khulna Development Authority'),
    ('123717','Khulna Shipyard Limited'),
    ('113214','Khulna University'),
    ('113220','Khulna University of Engineering & Technology'),
    ('902311','LP Gas Companies'),
    ('113377','Land Administration Training Centre (LATC)'),
    ('113460','Land Appeal Board'),
    ('915006','Land Lord'),
    ('909400','Land Mortgage Co-operative Bank'),
    ('113459','Land Reform Board'),
    ('902475','Laundry Services'),
    ('909200','Leasing Companies'),
    ('909220','Leasing Companies (Non-depository)'),
    ('902145','Leather Processing and Tanning (raw hide)'),
    ('902119','Leather Products ( bag, shoe, etc) Manufacturing Industries'),
    ('902474','Legal advisory Firms'),
    ('902485','Light Engineering and Metal-workshop'),
    ('122','Local Authorities'),
    ('113359','Madrasha Teachers Training Institute (MTTI)'),
    ('2121','Manufactures/Manufacturing Companies'),
    ('902147','Manufacturing of Electrical equipments & spares ( cables, bulbs, switches etc)'),
    ('902148','Manufacturing of Transport Equipments'),
    ('902509','Manufacturing of Unani and Ayurvedic Medicines/Herbal Cosmetics'),
    ('902149','Manufacturing of agro-equipments'),
    ('902504','Manufacturing of flour, sujee (Flour Mills)'),
    ('113323','Marine Fisheries Academy'),
    ('113236','Mawlana Bhashani Science & Technology University'),
    ('902515','Meat processing'),
    ('908200','Medical & Dental Colleges'),
    ('113206','Medical/Dental Colleges'),
    ('909240','Merchant Banks'),
    ('113439','Micro Credit Regulatory Authority (MRA)'),
    ('902123','Milk Processing Industries (Pasteurisation, milk powder, ice-cream, condensed milk, sweet, cheese, butter, ghee, chocolate, curd etc)'),
    ('915003','Minor/Autistics/Disabled and other dependent persons'),
    ('902464','Modernised Cleaning Service for High-rise Apartments, Commercial Building'),
    ('909700','Money Changers'),
    ('123520','Mongla Port Authority'),
    ('914051','Mosques'),
    ('124200','Municipal/City Corporation'),
    ('902520','Mustard oil producing industry (if local variety is used).'),
    ('909230','Mutual Funds'),
    ('112067','NGO Affairs Bureau'),
    ('909250','NGO/Micro Credit Organizations (BRAC, ASA, PROSHIKA etc.)'),
    ('113331','National Academy for Computer Training and Research (NACTAR)'),
    ('113330','National Academy for Educational Management (NAEM)'),
    ('113324','National Academy for Planning & Development'),
    ('113326','National Academy of Primary Education (NAEP)'),
    ('113455','National Board of Abandoned Properties'),
    ('112070','National Board of Revenue'),
    ('113374','National Book Centre, Bangladesh'),
    ('113101','National Curriculum and Text Book Board'),
    ('113472','National Foundation for Development of the Disabled Persons'),
    ('113471','National Foundation for Research on Human Resources'),
    ('113388','National Freedom Fighter Council'),
    ('113424','National Housing Authority'),
    ('113432','National Human Rights Commission'),
    ('113369','National Institute of Biotechnology'),
    ('113316','National Institute of Cardiovascular Diseases'),
    ('113319','National Institute of Disease of Chest & Hospital (NIDCH)'),
    ('113353','National Institute of Local Government'),
    ('113355','National Institute of Mass Communication (NIMCO)'),
    ('113320','National Institute of Ophthalmology'),
    ('113314','National Institute of Population, Research & Training (NIPORT)'),
    ('113317','National Institute of Preventive & Social Medicine (NIPSOM)'),
    ('113321','National Institute of Traumatology & Orthopedic Rehabilitation (NITOR)'),
    ('113361','National Legal Aid Institute'),
    ('113367','National Maritime Institute'),
    ('113389','National Museum of Science & Technology'),
    ('113386','National Sports Council (NSC)'),
    ('113329','National Training & Research Academy for Multilingual Shorthand, Bogra'),
    ('113204','National University (NU), Gazipur'),
    ('113356','Nazrul Institute'),
    ('907601','Newspaper'),
    ('214','Non Govt. Publicity & News Media'),
    ('123','Non-Bank Depository Corporations (NBDC) public'),
    ('221','Non-Bank Depository Corporations -Private'),
    ('21','Non-Financial Corporations'),
    ('113440','Non-Government Teachers Registration and Certification Authority ( NTRCA)'),
    ('24','Non-profit institutions serving households (NPISH)'),
    ('123435','North West Power Generation Company Ltd (NWPGC)'),
    ('112089','Office of the Assistant Commissioner of Land'),
    ('113479','Office of the Bangladesh Waqf Administrator'),
    ('112060','Office of the Chief Inspector of Boilers'),
    ('113447','Office of the Comptroller and Auditor General of Bangladesh'),
    ('112058','Office of the District Commissioner'),
    ('112059','Office of the Divisional Commissioner'),
    ('112057','Office of the Thana Executive Officer'),
    ('915005','Old/Widowed/Distressed person'),
    ('907604','Online News Media'),
    ('902599','Other Agro based Industries.'),
    ('914061','Other Associations, n.e.s.'),
    ('1134','Other Autonomous & Semi-autonomous bodies (Commission, Authority, Development Board/Centre/Foundations etc)'),
    ('903090','Other Business Institutions'),
    ('914054','Other Clubs'),
    ('909500','Other Co-operative Banks/Societies'),
    ('113399','Other Councils/Institutes'),
    ('909699','Other Depository Corporations'),
    ('908900','Other Educational /Training institutes /Technical Vocational Institute'),
    ('909799','Other Financial Auxiliaries'),
    ('909299','Other Financial Intermediaries'),
    ('124','Other Financial Intermediaries (OFI) except DMBs-Public'),
    ('222','Other Financial Intermediaries-- Private (Except DMBs).'),
    ('902313','Other Gas Companies'),
    ('902240','Other Industries not above mentioned'),
    ('124600','Other Local Authorities.'),
    ('915059','Other Local Individuals not above mentioned'),
    ('112099','Other Ministries, Directorates and Departments'),
    ('112','Other Ministries/Offices'),
    ('1216','Other Non-financial Public Corporations'),
    ('914063','Other Non-profit Organisations'),
    ('216','Other Private Sector ( Official Account n.i.e) '),
    ('113299','Other Public Educational Institutions'),
    ('12','Other Public Sector (Other Than Govt.)'),
    ('902490','Other Services'),
    ('121599','Others'),
    ('123719','Others'),
    ('123499','Others'),
    ('902319','Others'),
    ('121750','Others'),
    ('902467','Outsourcing and Security Service (Private Security forces/manpower supply)'),
    ('902312','Oxygen Gas Companies'),
    ('113237','Pabna University of Science and Technology'),
    ('902146','Packaging Industries including paper boards'),
    ('121515','Palli Karma-Sahayak Foundation (PKSF)'),
    ('123465','Pally Bidyut Samities'),
    ('122320','Paper and Paper Board Industries'),
    ('902121','Paper and Paper Products Manufacturing Industries'),
    ('113225','Patuakhali Science & Technology University'),
    ('113238','Patuakhali Science and Technology University'),
    ('121799','Pension Funds /Provident Funds of Government Offices'),
    ('909199','Pension Funds /Provident Funds of private organisations'),
    ('902127','Pharmaceutical Industries'),
    ('113379','Pharmacy Council of Bangladesh'),
    ('902451','Photo Studios and Color labs'),
    ('914056','Political Parties'),
    ('902156','Polymer and polythene industries'),
    ('901004','Poultry Farms'),
    ('123460','Power Cell'),
    ('123450','Power Grid Company of Bangladesh (PGCB)'),
    ('112037','Press Information Department'),
    ('113354','Press Institute of Bangladesh'),
    ('113404','Prime Ministers Relief Fund'),
    ('902111','Printing & Dyeing Industries'),
    ('215','Private Educational Institutions'),
    ('902459','Private Inland Container Depot and Container Freight Station'),
    ('908400','Private Institute of IT'),
    ('908100','Private Schools, Colleges, University Colleges & Madrashas'),
    ('2','Private Sector'),
    ('902476','Private Survey Institutions'),
    ('908300','Private Universities'),
    ('113414','Privatisation Commission'),
    ('121730','Probashi Kallyan Bank'),
    ('902502','Processed fruit products (jam, jelly, juice, pickles, asrbat, syrup, sauce etc.)'),
    ('902139','Processing of Prawn/Shrimp and other fishes and freezing'),
    ('902501','Processing of bread and biscuits, vermicelli, laccha, chanachur, noodles etc.'),
    ('902505','Processing of mushroom and spirulina'),
    ('902507','Processing of potato products (chips, potato, flex, starch etc.)'),
    ('902513','Processing of rubber tape, shellac'),
    ('902514','Production of bamboo and cane furniture (excluding cottage industry)'),
    ('902516','Production of bio slurry, mixed manure and urea.'),
    ('902517','Production of bio-pesticides, neem pesticides etc.'),
    ('902310','Production, supply and distribution of power in the private sector'),
    ('914059','Professional Associations (Doctors, Engineers, Statisticians, Economists etc.)'),
    ('910000','Professionals and Self-employed Persons (Such as Doctors, Lawyers, Contractors, Taxi Drivers, Architects, Consultants, etc)'),
    ('113375','Public Administration Training Centre, Savar & RPATC, Eskaton'),
    ('113467','Public Educational Funds'),
    ('121','Public Non-financial Corporations'),
    ('112061','Public Private Partnership Office'),
    ('1','Public Sector'),
    ('113463','Public Trust Funds'),
    ('112031','Public Works Department'),
    ('1135','Publicity And News Media'),
    ('905100','Publishing Industries (including printing press)'),
    ('902512','Pulse Mills'),
    ('907603','Radio'),
    ('113405','Rajdhani Unnayan Kartreepaksha (RAJUK)'),
    ('113408','Rajshahi Development Authority'),
    ('113211','Rajshahi University'),
    ('113221','Rajshahi University of Engineering & Technology'),
    ('113420','Rangamati Hill District Council'),
    ('112080','Rapid Action Battalion (RAB)'),
    ('902125','Readymade Garments Industries'),
    ('902135','Refining and hydrogenation of edible oil, vanaspati, Ghee etc'),
    ('113485','Registrar of Joint –Stock Companies and Firms'),
    ('112009','Registration Directorate'),
    ('902468','Residential Hotels ( Including 3star & Above)'),
    ('902450','Restaurants /Fast Food'),
    ('903050','Retail Traders'),
    ('915004','Retired Persons'),
    ('902118','Rice mills including puffed rice, chirra , fine rice, flavoured rice etc.'),
    ('113343','River Research Institute'),
    ('904001','Road Transport Companies (including Rent -a - car)'),
    ('112035','Roads and Highway Department'),
    ('902117','Rubber And Plastic Industries'),
    ('113302','Rural Development Academy, Bogra'),
    ('123410','Rural Electrification Board (REB)'),
    ('123455','Rural Power Company Ltd (RPCL)'),
    ('121518','SME Foundation'),
    ('121600','Sadharan Bima Corporation'),
    ('902128','Salt Processing Industries'),
    ('902479','Satellite Cable Operator'),
    ('902480','Satellite Channel Distributor/Cinema Distributors'),
    ('121510','Saudi Bangladesh Industrial and Agricultural Investment Company Limited (SABINCO).'),
    ('902215','Saw Mills'),
    ('113444','Seed Certification Agency'),
    ('902511','Seed processing and preservation'),
    ('2123','Service Industries'),
    ('113215','Shahjalal University of Science and Technology'),
    ('113478','Sheikh Zayad Bin Sultan Al Nahian Trust (Bangladesh)'),
    ('113223','Sher-e-Bangla Agricultural University'),
    ('902153','Ship Breaking Industries'),
    ('902152','Ship Building Industries'),
    ('902471','Shipping Agency'),
    ('902136','Soaps & Detergents Factories'),
    ('113363','Soil Resources Development Institute'),
    ('902519','Soya food production & processing.'),
    ('112077','Special Security Force'),
    ('902112','Spinning Mills'),
    ('914053','Sports Clubs'),
    ('902477','Sports and Event management organisation'),
    ('902506','Starch, glucose and other dextrose product'),
    ('902137','Steel Engineering & Metallic Products Industries (Including Rerolling Mills)'),
    ('122410','Steel Mills'),
    ('909710','Stock Exchanges (DSE, CSE, etc)'),
    ('902462','Stone Crashers'),
    ('915002','Student'),
    ('122210','Sugar Mills'),
    ('902142','Sugar Mills'),
    ('915051','Sundry Deposit, CIB Inquiry Charge, Clearing Adjustment Account, Inoperative Account, Suspense account etc.)'),
    ('902518','Sweetening products.'),
    ('113239','Sylhet Agricultural University'),
    ('902478','Tailoring Shop and Tailors'),
    ('902460','Tank Terminal'),
    ('902129','Tea processing industries'),
    ('905200','Telecommunication (Mobile/cellular operators and private land phone) Grameen Phone, Banglalink etc)'),
    ('123706','Telephone Shilpa Sangstha'),
    ('907602','Television'),
    ('914052','Temples, Churches & the like'),
    ('902456','Testing Laboratory'),
    ('1131','Text Book Board and Education Boards'),
    ('902120','Textile Mills'),
    ('124300','Thana/Upazila Parishad'),
    ('113417','The Security Printing Corporation (Bangladesh) Ltd.'),
    ('914055','Theatre & Cultural Organisations'),
    ('902115','Tobacco Processing Industries'),
    ('902457','Tourism Industry'),
    ('914057','Trade Unions'),
    ('122901','Trading Corporation of Bangladesh'),
    ('902452','Travel Agencies/Overseas Employment / Aviation Service/Immigration consultants/Ticket sales agent'),
    ('914062','Trust fund & Other Non-profit Organisations'),
    ('124400','Union Parishad'),
    ('113427','University Grants Commission of Bangladesh'),
    ('112023','Urban Development Directorate'),
    ('113477','Urban Development Trust'),
    ('113452','Vested Property Management Board'),
    ('123320','WASA (Dhaka, Chittagong, Khulna etc)'),
    ('911000','Wage & Salary Earners (working in the country)'),
    ('910500','Wage Earners (Bangladeshi nationals working abroad)'),
    ('906000','Warehouse'),
    ('113415','Water Resources Planning Organisation (WARPO)'),
    ('904002','Water Transport'),
    ('902113','Weaving Mills'),
    ('113464','Welfare Funds'),
    ('123440','West Zone Power Distribution Company Ltd (WZPDCL)'),
    ('903040','Whole Sale Traders'),
    ('124100','Zila Parishad'),
    ('902508','processing of powder spice')
)
CLRISK_LIST = (
    ('', 'Choose...'),
    ('1', 'High'),
    ('2', 'Medium'),
    ('3', 'Low'),
    ('4', 'N/A')
)
CLOCCUPATION_LIST = (
    ('', 'Choose...'),
    ('13','ADVOCATE'),
    ('22','ARMY'),
    ('23','Architect'),
    ('5','BUSINESSMAN'),
    ('24','Banker'),
    ('25','Business (Advertising)'),
    ('26','Business (Agency)'),
    ('27','Business (Car dealer, Car Repair, Car Finance)'),
    ('28','Business (Clearing and forwading)'),
    ('29','Business (Commission Agent)'),
    ('30','Business (Courier Service)'),
    ('31','Business (Dealership)'),
    ('33','Business (Export Sector)'),
    ('32','Business (Export and Import)'),
    ('34','Business (Garments /Buying House)'),
    ('35','Business (IT Sector)'),
    ('36','Business (Import Sector)'),
    ('37','Business (Indenting)'),
    ('38','Business (Indenting/Buying/Home/Imp/Exp/Agency)'),
    ('39','Business (Jewelry/ Gems/ Art/ Antique)'),
    ('40','Business (Manufacturing)'),
    ('41','Business (Money Changer)'),
    ('42','Business (Music)'),
    ('43','Business (Other Local Business)'),
    ('44','Business (Petrol Pump/CNG Station)'),
    ('45','Business (Real Estate/ Construction)'),
    ('46','Business (Supply)'),
    ('47','Business (Tour Guide)'),
    ('48','Business (Trading, Retail)'),
    ('49','Business (Transportation)'),
    ('50','Business (Travel Agency/ Air Ticketing)'),
    ('51','Business (Travel Agency/Tour Guide/Transportation)'),
    ('52','Business (hotel/restaurant/bar)'),
    ('53','Business (pharmaceuticals)'),
    ('54','Business (stock broker/ Dealer)'),
    ('4','CHARTER ACCOUNTANT'),
    ('11','CLERK'),
    ('2','DOCTOR'),
    ('55','Defense Service (Commissioned Officer)'),
    ('56','Defense Service (Non-Commissioned)'),
    ('57','Director Private Limited Company'),
    ('58','Director Public Limited Company'),
    ('3','ENGINEER'),
    ('21','FOOTBAL PLAYER'),
    ('59','Farmar'),
    ('12','GOVERNMENT EMPLOYEE'),
    ('60','Government Service - Non-Officer'),
    ('61','Government Service - Officer'),
    ('7','HOUSE HOLD'),
    ('15','HOUSE WIFE'),
    ('6','INDUSTRIALIST'),
    ('18','INSURANCE COMPANIES'),
    ('8','INVESTOR'),
    ('62','Journalist'),
    ('63','Judiciary'),
    ('64','Land Lord'),
    ('65','Lawyear'),
    ('99','OTHER'),
    ('19','OTHER COUNCILS/INSTITUTES'),
    ('16','OTHER MINISTRIES/OFFICERS'),
    ('66','Pilot / Flight Attendant'),
    ('67','Player'),
    ('68','Police, Customs, Tax'),
    ('69','Private Service (Managerial)'),
    ('70','Private Service (non-managerial)'),
    ('71','Professor'),
    ('72','Retired individual'),
    ('1','SERVICE'),
    ('20','STEEL MILLS'),
    ('14','STUDENT'),
    ('73','Self employed professional'),
    ('74','Service (Abroad)'),
    ('76','Service (Airlines)'),
    ('75','Service (IT Sector)'),
    ('77','Service (Others)'),
    ('78','Service (Pharmaceuticals)'),
    ('79','Service - State Owned Enterprise (managerial)'),
    ('80','Service - State Owned Enterprise (non-managerial)'),
    ('9','TEACHER'),
    ('17','WAGE & SALARY EARNERS'),
    ('10','WORKER')
)
CLACCOMTYPE_LIST = (
    ('', 'Choose...'),
    ('1', 'Own Independent House'),
    ('2', 'Own Flat'),
    ('3', 'On Rental'),
    ('4', 'Company Provided'),
    ('5', 'Joint Family'),
    ('6', 'Others')
)
CLEDUCATION_LIST = (
    ('', 'Choose...'),
    ('PSC', 'Primary School Certificate'),
    ('JSC', 'Junior School Certificate'),
    ('SSC', 'Secondary School Certificate'),
    ('HSC', 'Higher School Certificate'),
    ('HON', 'Honors Degree'),
    ('MAS', 'Mastrers Degree'),
    ('PHD', 'PHD Degree'),
)
RELEGION_LIST = (
    ('', 'Choose...'),
    ('I', 'Islam'),
    ('H', 'Hindu'),
    ('B', 'Boddis'),
    ('C', 'Cristian'),
    ('O', 'Others')
)
currency_list = (
    ('BDT', 'Bangladeshi Taka'),
    ('USD', 'US Dollar'),
    ('CAT', 'Canadian Dollar')
)
BLOOD_GRP_LIST = (
    ('', 'Choose...'),
    ('A+', 'A+'),
    ('AB+', 'AB+'),
    ('B+', 'B+'),
    ('O+', 'B-'),
    ('A-', 'A-'),
    ('AB-', 'AB-'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-')
)
marital_status=(
    ('', 'Choose...'),
    ('S','Single'),
    ('M','Married'),
    ('O','Others')
)

CLINCOMESLAB_LIST = (
    ('', 'Choose...'),
    ('1','1 - <= 1 Lakh'),
    ('2','> 1 Lakh - <= 2.5 Lakh'),
    ('3','> 2.5 Lakh - <= 5 Lakh'),
    ('4','Above 5 Lakh')
)

ACSTATEFREQ_LIST = (
    ('', 'Choose...'),
    ('D','Daily'),
    ('W','Weekly'),
    ('F','Fortnightly'),
    ('M','Monthly'),
    ('Q','Quarterly'),
    ('H','Half Yearly')
)
ACOPENWAY_LIST = (
    ('', 'Choose...'),
    ('1','Mobilied by Staff'),
    ('3','OTHER MARKETING CHANNELS'),
    ('2','Walk-in-customer')
)

ACMODEOFOPERATION_LIST = (
    ('', 'Choose...'),
    ('1','SELF'),
    ('2','ANYONE'),
    ('3','JOINTLY'),
    ('4','JOINTLY ANY TWO'),
    ('5','EITHER OR SURVIVOR'),
    ('6','GUARDIAN'),
    ('7','JOINTLY GUARDIAN'),
    ('8','ANY ONE GUARDIAN'),
    ('9','POWER OF ATTORNEY'),
    ('10','ANY DIRECTOR'),
    ('11','ANY ONE PARTNER'),
    ('12','OTHERS')
)

class clients_models(models.Model):
    client_id = models.IntegerField()
    client_name = models.CharField(max_length=200)
    client_type = models.CharField(max_length=20, default='',choices=CLTYPE_LIST)
    client_category = models.CharField(max_length=20, default='',choices=CLCAT_LIST)
    client_segment_code = models.CharField(max_length=10, default='', choices= CLSEGMENT_LIST)
    client_father_name = models.CharField(max_length=200, blank=True)
    client_mother_name = models.CharField(max_length=200, blank=True)
    client_blood_group = models.CharField(max_length=4, default='',choices=BLOOD_GRP_LIST, blank=False)
    client_sex = models.CharField(max_length=5,null=True,choices=SEX_LIST,default='')
    client_religion = models.CharField(max_length=2, default='',choices=RELEGION_LIST ,blank=False)
    client_marital_status = models.CharField(max_length=2,null=True, default ='', choices=marital_status, blank=False) #choices=marital_status,
    client_national_id = models.CharField(max_length=200,null=True)
    client_nationality     = models.CharField(max_length=200, default='Bangladeshi', null=False)
    client_tin_number = models.CharField(max_length=200,null=True, blank = True)
    client_present_address = models.TextField(null=True, blank=True)
    client_permanent_address = models.TextField(null=True, blank=True)
    client_risk_category = models.CharField(max_length=20, default='', choices= CLRISK_LIST)
    client_tds_exemption = models.BooleanField(default=False)
    client_annual_limit = models.IntegerField(null=True, default=0, blank=True)
    client_monthly_limit = models.IntegerField(null=False, default=0)
    client_occupation_code = models.CharField(max_length= 200, default='', choices=CLOCCUPATION_LIST)
    client_accom_type = models.CharField(max_length= 20, default= '', choices= CLACCOMTYPE_LIST)
    client_have_insurance_policy = models.BooleanField(default=False)
    client_plan_for_insurance_policy = models.BooleanField(default=False)
    client_phone = models.CharField(max_length=15,null=True)
    client_email = models.CharField(max_length=30,null=True, blank=True)
    client_opening_date = models.DateField(auto_now_add=True)
    client_education       = models.CharField(max_length=200, null=False, choices=CLEDUCATION_LIST)
    client_date_of_birth = models.DateField(null=False)
    client_birth_place     = models.CharField(max_length=200, default='',null=False)
    client_monthly_income  = models.IntegerField(null=False, default=0)
    client_annual_income   = models.IntegerField(null=True, default=0, blank=True)
    client_annual_income_slab  = models.CharField(max_length=20, null= True, default = '', blank = True, choices= CLINCOMESLAB_LIST)
    client_number_of_debit_tran_a_month = models.FloatField(null=False, default=0, blank=False)
    client_number_of_credit_tran_a_month = models.FloatField(null=False, default=0, blank=False)
    client_amount_of_debit_tran_a_month = models.FloatField(null=False, default=0, blank=False)
    client_amount_of_credit_tran_a_month = models.FloatField(null=False, default=0, blank=False)
    client_number_of_debit_tran_a_year = models.FloatField(null=False, default=0, blank=False)
    client_number_of_credit_tran_a_year = models.FloatField(null=False, default=0, blank=False)
    client_amount_of_debit_tran_a_year = models.FloatField(null=False, default=0, blank=False)
    client_amount_of_credit_tran_a_year = models.FloatField(null=False, default=0, blank=False)
    app_user_id  = models.CharField(max_length=20, null=False)
    app_data_time = models.DateTimeField(auto_now_add=True)

class Inventory_Number(models.Model):
    inv_code = models.IntegerField()
    branch_code =  models.IntegerField(null=True)
    app_user_id = models.IntegerField(null=True)
    inv_prefix = models.CharField(max_length=3)
    last_used_number = models.IntegerField()
    inv_naration = models.CharField(max_length=200)

    def __str__(self):
        return self.inv_naration

class account_model(models.Model):
    account_number = models.CharField(max_length=15, default='', null=False)
    account_client_code = models.IntegerField(null=False, default= 0)
    account_product_code = models.IntegerField(null=False, default= 0)
    account_open_date = models.DateField(auto_now_add=True)
    account_manual_account_number = models.BooleanField(default=False)
    account_preferred_account_number = models.CharField(max_length=15, default='', null=True, blank=True)
    account_name = models.CharField(max_length= 100, null=False, default = '')
    account_salary_account = models.BooleanField(default = False)
    account_statement_required = models.BooleanField(default = True)
    account_statement_frequency = models.CharField(max_length=20, default='H', null = False, choices= ACSTATEFREQ_LIST)
    account_opening_way = models.CharField(max_length=20, default='', choices= ACOPENWAY_LIST)
    account_mode_of_operation = models.CharField(max_length=50, default='', choices=ACMODEOFOPERATION_LIST)
    account_interest_required = models.BooleanField(default = True)
    account_nomination_required  = models.BooleanField(default = True)
    account_nominee_account_number = models.CharField(max_length=20, null = True, blank=True)
    account_nominee_client_number = models.CharField(max_length=20, null = True, blank=True)
    account_nominee_name = models.CharField(max_length=100, null = False)
    account_nominee_DOB = models.DateField(null = True)
    account_nominee_address = models.TextField(null=True, blank=True)
    account_nominee_mobile = models.CharField(max_length= 15)
    account_share_parcentage = models.DecimalField(null = False, default= 0, max_digits= 100, decimal_places= 2)
    account_atm_operation_permitted = models.BooleanField(default=True)
    account_internet_banking_Permitted = models.BooleanField(default=False)
    account_sms_Permitted = models.BooleanField(default=True)
    account_women_entrepreneurs = models.BooleanField(default=False)
    app_user_id  = models.CharField(max_length=20, null=False)
    app_data_time = models.DateTimeField(auto_now_add=True)


class prediction_model(models.Model):
    user_client_code = models.IntegerField(null=False, default= 0)
