# Generated by Django 3.0 on 2019-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='', max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('', 'Choose...'), ('I', 'Individual'), ('C', 'Corporate'), ('J', 'Joint'), ('O', 'Others')], default='', max_length=20)),
                ('client_referred_by', models.CharField(blank=True, max_length=15, null=True)),
                ('client_father_name', models.CharField(blank=True, max_length=200)),
                ('client_mother_name', models.CharField(blank=True, max_length=200)),
                ('client_blood_group', models.CharField(blank=True, choices=[('', 'Choose...'), ('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'B-'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('O-', 'O-')], default='', max_length=4)),
                ('client_sex', models.CharField(choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=5, null=True)),
                ('client_religion', models.CharField(blank=True, choices=[('', 'Choose...'), ('I', 'Islam'), ('H', 'Hindu'), ('B', 'Boddis'), ('C', 'Cristian')], default='', max_length=2)),
                ('client_marital_status', models.CharField(blank=True, choices=[('', 'Choose...'), ('S', 'Single'), ('M', 'Merit'), ('O', 'Others')], default='', max_length=2, null=True)),
                ('client_national_id', models.CharField(max_length=200, null=True)),
                ('client_nationality', models.CharField(default='Bangladeshi', max_length=200)),
                ('client_present_address', models.TextField(blank=True, null=True)),
                ('client_permanent_address', models.TextField(blank=True, null=True)),
                ('client_phone', models.CharField(max_length=15, null=True)),
                ('client_email', models.CharField(blank=True, max_length=30, null=True)),
                ('client_joining_date', models.DateField(blank=True, null=True)),
                ('client_education', models.CharField(max_length=200)),
                ('client_date_of_birth', models.DateField(blank=True, null=True)),
                ('client_wise_clent_code', models.CharField(max_length=10)),
                ('client_center_code', models.CharField(max_length=10, null=True)),
                ('client_birth_place', models.CharField(default='Narsingdi', max_length=200)),
                ('client_monthly_income', models.IntegerField()),
                ('client_annual_income', models.IntegerField()),
                ('client_admit_fee', models.IntegerField()),
                ('client_memo_num', models.CharField(max_length=200)),
                ('app_user_id', models.CharField(max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
