# Generated by Django 3.0 on 2019-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0002_auto_20191206_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_code', models.IntegerField()),
                ('branch_code', models.IntegerField(null=True)),
                ('app_user_id', models.IntegerField(null=True)),
                ('inv_prefix', models.CharField(max_length=3)),
                ('last_used_number', models.IntegerField()),
                ('inv_naration', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
