# Generated by Django 3.0 on 2019-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0003_auto_20191206_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_models',
            name='client_marital_status',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('S', 'Single'), ('M', 'Merried'), ('O', 'Others')], default='', max_length=2, null=True),
        ),
    ]
