# Generated by Django 3.0 on 2019-12-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0004_auto_20191206_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_models',
            name='client_have_insurance_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_plan_for_insurance_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_blood_group',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'B-'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_religion',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('I', 'Islam'), ('H', 'Hindu'), ('B', 'Boddis'), ('C', 'Cristian'), ('O', 'Others')], default='', max_length=2),
        ),
    ]
