# Generated by Django 3.0 on 2019-12-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0005_auto_20191207_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=15)),
                ('account_client_code', models.IntegerField(default=0)),
                ('account_product_code', models.IntegerField(default=0)),
                ('account_open_date', models.DateField(auto_now_add=True)),
                ('account_manual_account_number', models.BooleanField(default=False)),
                ('account_preferred_account_number', models.CharField(default='', max_length=15)),
                ('account_name', models.CharField(default='', max_length=100)),
                ('account_salary_account', models.BooleanField(default=False)),
                ('account_statement_required', models.BooleanField(default=True)),
                ('account_statement_frequency', models.CharField(choices=[('', 'Choose...'), ('D', 'Daily'), ('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half Yearly')], default='H', max_length=20)),
                ('account_opening_way', models.CharField(choices=[('', 'Choose...'), ('1', 'Mobilied by Staff'), ('3', 'OTHER MARKETING CHANNELS'), ('2', 'Walk-in-customer')], default='', max_length=20)),
                ('account_mode_of_operation', models.CharField(choices=[('', 'Choose...'), ('1', 'SELF'), ('2', 'ANYONE'), ('3', 'JOINTLY'), ('4', 'JOINTLY ANY TWO'), ('5', 'EITHER OR SURVIVOR'), ('6', 'GUARDIAN'), ('7', 'JOINTLY GUARDIAN'), ('8', 'ANY ONE GUARDIAN'), ('9', 'POWER OF ATTORNEY'), ('10', 'ANY DIRECTOR'), ('11', 'ANY ONE PARTNER'), ('12', 'OTHERS')], default='', max_length=50)),
                ('account_interest_required', models.BooleanField(default=True)),
                ('account_nomination_required', models.BooleanField(default=True)),
                ('account_nominee_account_number', models.CharField(max_length=20, null=True)),
                ('account_nominee_client_number', models.CharField(max_length=20, null=True)),
                ('account_nominee_name', models.CharField(max_length=100)),
                ('account_nominee_DOB', models.DateField(null=True)),
                ('account_nominee_address', models.TextField(blank=True, null=True)),
                ('account_nominee_mobile', models.CharField(max_length=15)),
                ('account_share_parcentage', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('account_atm_operation_permitted', models.BooleanField(default=True)),
                ('account_internet_banking_Permitted', models.BooleanField(default=False)),
                ('account_sms_Permitted', models.BooleanField(default=True)),
                ('account_women_entrepreneurs', models.BooleanField(default=False)),
                ('app_user_id', models.CharField(max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_date_of_birth',
            field=models.DateField(),
        ),
    ]
