# Generated by Django 3.0 on 2019-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0006_auto_20191207_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='prediction_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_client_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='account_model',
            name='account_nominee_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account_model',
            name='account_nominee_client_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account_model',
            name='account_preferred_account_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
