# Generated by Django 3.0 on 2019-12-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0007_auto_20191212_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_models',
            name='client_amount_of_credit_tran_a_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_amount_of_credit_tran_a_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_amount_of_debit_tran_a_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_amount_of_debit_tran_a_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_number_of_credit_tran_a_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_number_of_credit_tran_a_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_number_of_debit_tran_a_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clients_models',
            name='client_number_of_debit_tran_a_year',
            field=models.FloatField(default=0),
        ),
    ]
