# Generated by Django 3.0 on 2019-12-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0009_clients_models_client_annual_income_slab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients_models',
        ),
    ]
