# Generated by Django 3.0 on 2019-12-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0011_clients_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_models',
            name='client_blood_group',
            field=models.CharField(choices=[('', 'Choose...'), ('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'B-'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_marital_status',
            field=models.CharField(choices=[('', 'Choose...'), ('S', 'Single'), ('M', 'Merried'), ('O', 'Others')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_religion',
            field=models.CharField(choices=[('', 'Choose...'), ('I', 'Islam'), ('H', 'Hindu'), ('B', 'Boddis'), ('C', 'Cristian'), ('O', 'Others')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_tin_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
