# Generated by Django 3.0 on 2019-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLProduct', '0012_auto_20191213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_models',
            name='client_annual_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_annual_income_slab',
            field=models.CharField(choices=[('', 'Choose...'), ('1', '1 - <= 1 Lakh'), ('2', '> 1 Lakh - <= 2.5 Lakh'), ('3', '> 2.5 Lakh - <= 5 Lakh'), ('4', 'Above 5 Lakh')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients_models',
            name='client_annual_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
